---
name: suividevente
description: Application permettant de suivre les ventes selon une journée ou autres
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.1.0
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  animated_text_kit: ^4.2.1
  provider: ^6.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.7
  syncfusion_flutter_calendar: ^19.2.60
  syncfusion_localizations: ^19.2.60
  flutter_sheet_localization: ^5.1.1
  localization: ^1.0.0
  animate_do: ^2.0.0
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.1
  firebase_storage: ^10.0.3
  flutter_spinkit: ^5.1.0
  animated_splash_screen: ^1.1.0
  image_picker: ^0.8.4
  path: ^1.8.0
  file_picker: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
  assets:
  - assets/background/
